version: '3'

services:
  frontend:
    build:
      context: ./frontend
#    https://github: com/vitejs/vite/issues/2671#issuecomment-829535806:
    command: sh -c "npm rebuild esbuild && npm run dev"
    environment:
      PORT: '8080'
      HOST: '0.0.0.0'
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/frontend
